Do not inject context variable unless running within a jupyter notebook
nuclio/nuclio-jupyter pull request #152
Opened 2022-11-23 10:22 UTC by yaelgen

2022-11-27 14:10 UTC, AlonMaor14 requested changes
Looks great! 
Can you please add a description for the PR explaining why this change was needed?
Also please add a test that `context` is not being imported when not running in jupyter notebook.

2022-11-27 14:10 UTC, AlonMaor14 commented on tests/test_request.py
> +        context  # noqa - Make sure it's there
missing new line at EOF

2022-11-27 14:19 UTC, liranbg commented on nuclio/request.py
> +    return False
newline

2022-11-28 06:50 UTC, AlonMaor14 approved these changes

2022-11-28 06:51 UTC, merged