[IG-21881] Delete hard-coded attributes in KafkaTrigger
nuclio/nuclio-jupyter pull request #171
Opened 2023-08-30 13:44 UTC by rokatyy

Jira: `IG-21881`

* Delete hard-coded attributes in KafkaTrigger
*  Set workerAllocationMode to "static" by default when explicit ack is enabled

2023-08-30 14:13 UTC, TomerShor requested changes

2023-08-30 14:13 UTC, TomerShor commented on nuclio/triggers.py
> +            # workerAllocationMode conflicts with explicit_ack_mode, so we should force static one in that case
Maybe raise exception / log in case of forcing it?
So user will be aware that it changed.

2023-09-04 09:07 UTC, liranbg commented on nuclio/triggers.py
> +                extra_attributes["workerAllocationMode"] = "static"
```python
if not extra_attributes:
  extra_attributes = {}
extra_attributes.setdefault("workerAllocationMode", "static")
```

2023-09-04 19:31 UTC, liranbg approved these changes

2023-09-05 18:42 UTC, merged